# docker-compose.yml
version: '3.9'

services:
  web:
    build: .
    ports:
      - "23054:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_USER=django_user
      - DJANGO_DB_PASSWORD=secure_password
      - DJANGO_DB_NAME=django_db
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "24054:5432"
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: django_db